import LocaleLabel from "./LocaleLabel";
import Localized from "./Localized";
import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useLocale } from '../i18n/LocaleContext';
import useDocumentMeta from '../hooks/useDocumentMeta';
import { getLifeEvent, getWealthNode, EVENT_STATUSES, downloadTemplate, EDUCATIONAL_DISCLAIMER } from '../features/lifeCapitalMap';
import NotFound from './NotFound';
import styles from './CapitalMap.module.css';
export default function CapitalEventPage() {
  const {
      id
    } = useParams(),
    {
      localePath
    } = useLocale(),
    event = getLifeEvent(id),
    [status, setStatus] = useState('watch');
  useDocumentMeta(event ? `${event.title} | ONYX Event Radar` : 'Event not found', event?.description || '');
  if (!event) return <NotFound />;
  return <main className={`${styles.shell} ${styles.detail} page-enter`}><Link className={styles.back} to={localePath('/capital-map/events')}><Localized en={<>← Event Radar</>} zh={<>事件雷达</>} /></Link><header className={styles.detailHero}><p><LocaleLabel value={event.category.replace('_', ' ')} /></p><h1><Localized en={<><LocaleLabel value={event.title} /></>} zh={<><LocaleLabel value={event.titleZh} /></>} /></h1><p><Localized en={<><LocaleLabel value={event.description} /></>} zh={<><LocaleLabel value={event.descriptionZh} /></>} /></p></header>
<section className={styles.status}><h2><Localized en={<>Where is this event now? </>} zh={<>这个事件目前在哪里？</>} /></h2><p><Localized en={<>Your selection stays only on this page and is not saved or submitted.</>} zh={<>你的选择只停留在当前页面，不会保存或提交。</>} /></p><div>{EVENT_STATUSES.map(item => <button type="button" key={item.id} aria-pressed={status === item.id} onClick={() => setStatus(item.id)}><Localized en={<><LocaleLabel value={item.label} /></>} zh={<><LocaleLabel value={item.labelZh} /></>} /></button>)}</div><div className={styles.selectedStatus} aria-live="polite"><strong><Localized en={<><LocaleLabel value={EVENT_STATUSES.find(item => item.id === status).description} /></>} zh={<><LocaleLabel value={EVENT_STATUSES.find(item => item.id === status).descriptionZh} /></>} /></strong></div></section>
<section className={styles.story}><span><Localized en={<>STORY</>} zh={<>生活案例</>} /></span><h2><Localized en={<><LocaleLabel value={event.story.title} /></>} zh={<><LocaleLabel value={event.story.titleZh} /></>} /></h2><p><Localized en={<><LocaleLabel value={event.story.body} /></>} zh={<><LocaleLabel value={event.story.bodyZh} /></>} /></p></section>
<section className={styles.eventSections}><article><span><LocaleLabel value={"WHAT MAY BE HAPPENING"} /></span><p><Localized en={<><LocaleLabel value={event.description} /></>} zh={<><LocaleLabel value={event.descriptionZh} /></>} /></p></article><article><span><LocaleLabel value={"WHY THIS MATTERS"} /></span><p><Localized en={<><LocaleLabel value={event.whyItMatters.body} /></>} zh={<><LocaleLabel value={event.whyItMatters.bodyZh} /></>} /></p></article><article><span><LocaleLabel value={"PLANNING WINDOW"} /></span><p><Localized en={<><LocaleLabel value={event.planningWindow.body} /></>} zh={<><LocaleLabel value={event.planningWindow.bodyZh} /></>} /></p><p><Localized en={<>Depending on the facts, current tax rules should be verified before implementation.</>} zh={<>具体处理取决于事实，执行前应核实当时有效的税务规则。</>} /></p></article><article><span><LocaleLabel value={"TOPICS WORTH REVIEWING"} /></span><ul>{event.taxTopics.map(x => <li key={x}><LocaleLabel value={x} /></li>)}</ul></article><article><span><LocaleLabel value={"RECORDS TO GATHER"} /></span><ul>{event.recordsNeeded.map(x => <li key={x}><LocaleLabel value={x} /></li>)}</ul></article><article><span><LocaleLabel value={"QUESTIONS WORTH ASKING"} /></span><ul>{event.questionsWorthAsking.map(x => <li key={x}><LocaleLabel value={x} /></li>)}</ul></article><article><span><LocaleLabel value={"COMMON BLIND SPOTS"} /></span><ul>{event.blindSpots.map(x => <li key={x}><LocaleLabel value={x} /></li>)}</ul></article></section>
<section className={styles.guidance}><article><span><LocaleLabel value={"SELF-MANAGE?"} /></span><h2><Localized en={<>What you may organize yourself</>} zh={<>可以先自行整理什么</>} /></h2><p><Localized en={<><LocaleLabel value={event.selfManage.body} /></>} zh={<><LocaleLabel value={event.selfManage.bodyZh} /></>} /></p></article><article><span><LocaleLabel value={"DEEPER REVIEW?"} /></span><h2><Localized en={<>When deeper review may help</>} zh={<>何时值得进一步梳理</>} /></h2><p><Localized en={<><LocaleLabel value={event.deeperReview.body} /></>} zh={<><LocaleLabel value={event.deeperReview.bodyZh} /></>} /></p><ul>{event.deeperReview.triggers.map(x => <li key={x}><LocaleLabel value={x} /></li>)}</ul></article></section>
<section className={styles.keep}><span><Localized en={<>KEEP</>} zh={<>下载工具</>} /></span><h2><Localized en={<>Event Preparation Checklist</>} zh={<>事件准备清单</>} /></h2><button type="button" onClick={() => downloadTemplate('event-preparation')}><Localized en={<>Download CSV</>} zh={<>下载CSV</>} /></button><p><LocaleLabel value={"Use nicknames and document locations; do not place sensitive identifiers in this worksheet."} /></p></section>
<section className={styles.related}><h2><Localized en={<>Related Nodes</>} zh={<>相关节点</>} /></h2>{event.relatedNodes.map(id => {
        const node = getWealthNode(id);
        return node ? <Link key={id} to={localePath(`/capital-map/node/${id.toLowerCase()}`)}><LocaleLabel value={node.id} /> · <Localized en={<><LocaleLabel value={node.title} /></>} zh={<><LocaleLabel value={node.titleZh} /></>} /></Link> : null;
      })}</section>
<section className={styles.insights}><h2><Localized en={<>Related Insight Seeds</>} zh={<>内容种子</>} /></h2>{event.insightSeeds.map(seed => <div key={seed.type}><span><LocaleLabel value={seed.type} /></span><strong><Localized en={<><LocaleLabel value={seed.title} /></>} zh={<><LocaleLabel value={seed.titleZh} /></>} /></strong><em><Localized en={<>Planned</>} zh={<>计划中</>} /></em></div>)}</section>
<section className={styles.askSammi}><span><LocaleLabel value={"ASK SAMMI"} /></span><h2><LocaleLabel value={event.cta || 'Organize the event before the choices narrow.'} /></h2><p><LocaleLabel value={"Current status: "} /><LocaleLabel value={status} /><LocaleLabel value={". No sensitive document upload is requested."} /></p><Link to={`${localePath('/contact')}?context=${encodeURIComponent(event.askSammiContext)}&eventStatus=${status}`}><Localized en={<>Ask Sammi with context</>} zh={<>带背景联系Sammi</>} /></Link></section><footer className={styles.disclaimer}><p><Localized en={<><LocaleLabel value={EDUCATIONAL_DISCLAIMER.en} /></>} zh={<><LocaleLabel value={EDUCATIONAL_DISCLAIMER.zh} /></>} /></p></footer></main>;
}
