import { Link } from 'react-router-dom'
import { useLocale } from '../i18n/LocaleContext'
import useDocumentMeta from '../hooks/useDocumentMeta'
import BeforeYouAct from './BeforeYouAct'
import FutureFlexibilityImpact from './FutureFlexibilityImpact'
import { JOB_CHANGE_EVENT, OLD_401K_DECISION, ROLLOVER_KNOWLEDGE, localizeDecision } from '../features/decisionIntelligence'
import { EDUCATIONAL_GUIDANCE_DISCLAIMER } from '../data/v3Brand'
import styles from './DecisionGuidePage.module.css'

export default function DecisionGuidePage() {
  const {locale,localePath}=useLocale(), zh=locale==='zh', l=value=>localizeDecision(value,locale), d=OLD_401K_DECISION
  useDocumentMeta(`${l(d.title)} · ONYX`,l(JOB_CHANGE_EVENT.summary))
  const context=[`${zh?'你正在了解':'You are exploring'}: ${l(d.sammiReviewContext.exploring)}`,`${zh?'容易忽略的关联':'Potential hidden connection'}: ${l(d.sammiReviewContext.hidden)}`,`${zh?'可先准备':'Useful information to gather'}: ${l(d.sammiReviewContext.gather)}`,`${zh?'值得梳理的问题':'Questions worth reviewing'}: ${l(d.sammiReviewContext.questions)}`].join('\n')
  return <main className={`${styles.page} page-enter`}>
    <header className={styles.hero}><p>{zh?'BUILD FOR TOMORROW · 退休规划':'BUILD FOR TOMORROW · RETIREMENT PLANNING'}</p><h1>{l(JOB_CHANGE_EVENT.title)}</h1><p className={styles.summary}>{l(JOB_CHANGE_EVENT.summary)}</p><div className={styles.windows}>{JOB_CHANGE_EVENT.planningWindows.map(item=><span key={l(item)}>{l(item)}</span>)}</div><div className={styles.focus}><small>{zh?'这次先看清一个决定':'ONE DECISION TO UNDERSTAND NOW'}</small><h2>{l(d.question)}</h2><p>{l(d.whatPeopleUsuallyDo)}</p></div></header>
    <section className={styles.story}><p className={styles.eyebrow}>{zh?'一个虚构的学习案例':'A FICTIONAL EDUCATIONAL EXAMPLE'}</p><h2>{zh?'Lisa 换工作以后，先停下来问了一步':'Lisa paused before choosing a destination'}</h2><p>{zh?'Lisa 今年 43 岁，最近换了工作。她在原公司 401(k) 里大约有 30 万美元。把资金全部转进一个 IRA，听起来很方便。可是在行动前，黑曜多问了一句：这笔钱今天转到哪里，会不会影响她以后想做的 Roth 规划？Lisa 只是用于说明问题的虚构人物，并不代表当前读者。':"Lisa is 43 and recently changed jobs. Her former employer's 401(k) has approximately $300,000. Moving everything into one IRA sounds convenient. Before she acts, ONYX asks one more question: could where the money lands today affect Roth planning she may want later? Lisa is fictional and does not represent the current reader."}</p></section>
    <section className={styles.moment}><p className={styles.eyebrow}>{zh?'你原本可能不知道要问的问题':'THE QUESTION YOU DIDN’T KNOW TO ASK'}</p><h2>{zh?'旧 401(k) 今天转到哪里，会不会影响以后做 Roth 规划的空间？':'Could where I move my old 401(k) today affect future Roth-planning flexibility?'}</h2><h3>{zh?'为什么这可能很重要':'WHY THIS MAY MATTER'}</h3><p>{l(d.whatTheyMayNotRealize)}</p><p>{zh?'把税前退休资金从 qualified employer plan 转入 Traditional IRA / Rollover IRA，会改变 IRA 体系中的税前余额。以后评估某些 Roth conversion 或 Backdoor Roth 安排时，IRA basis 与税前 IRA 余额可能在 pro-rata rule 下相互关联。这里先说明关联，不计算任何人的税务结果。':'Moving pre-tax retirement money from a qualified employer plan into a Traditional/Rollover IRA changes the pre-tax money held inside the IRA system. That can matter when evaluating certain future Roth conversion or Backdoor Roth strategies because IRA basis and pre-tax IRA balances may interact under pro-rata rules. This page identifies the connection; it does not calculate anyone’s tax result.'}</p></section>
    <section className={styles.map}><p className={styles.eyebrow}>{zh?'选择地图':'VISUAL DECISION MAP'}</p><h2>{l(d.question)}</h2><div className={styles.origin}>OLD 401(k)</div><div className={styles.choiceGrid}>{d.choices.map((choice,index)=><article key={l(choice)}><span>0{index+1}</span><strong>{l(choice)}</strong>{index===2&&<small>{zh?'可能影响以后 IRA / Roth 规划':'May affect future IRA / Roth planning'}</small>}{index===3&&<small>{zh?'税务后果可能不同':'Tax consequences may differ'}</small>}</article>)}</div><p>{zh?'这里没有推荐分支。不是每个计划都会提供所有选择。':'No branch is recommended. Not every option is available under every plan.'}</p></section>
    <FutureFlexibilityImpact data={d.futureFlexibilityImpact} localize={l}/>
    <section className={styles.tradeoffs}><p className={styles.eyebrow}>{zh?'选择与取舍':'CHOICES & TRADE-OFFS'}</p><h2>{zh?'不要只比较“方不方便”':'Compare more than convenience'}</h2>{d.tradeoffs.map(item=><article key={l(item)}>{l(item)}</article>)}</section>
    <BeforeYouAct decision={d} localize={l}/>
    <section className={styles.facts}><p className={styles.eyebrow}>{zh?'讲到这里，个人事实开始重要':'THIS IS WHERE YOUR FACTS MATTER'}</p><h2>{zh?'公开知识可以帮你看见问题，但不能替你作出这项决定。':'Public education can reveal the issue. It cannot make this decision for you.'}</h2><ul>{(zh?['退休账户整体结构','现有 IRA 余额与 basis','原计划与新计划规则','当前与预期收入','行动时间','退休目标','未来 Roth 规划']:['Retirement account structure','Existing IRA balances and basis','Old and new plan rules','Current and expected income','Timing','Retirement goals','Future Roth strategy']).map(item=><li key={item}>{item}</li>)}</ul><p>{l(d.reviewTrigger)}</p></section>
    <section className={styles.learning}><p className={styles.eyebrow}>{zh?'想多了解一点（可选）':'OPTIONAL DEEPER LEARNING'}</p>{ROLLOVER_KNOWLEDGE.map(item=><details key={item.id}><summary>{l(item.title)}</summary><p>{l(item.body)}</p></details>)}</section>
    <section className={styles.handoff}><p className={styles.eyebrow}>{zh?'下一步':'NEXT MOVE'}</p><h2>{zh?'和 Sammi 一起梳理我的退休账户转换选择':'Review My Retirement Transition with Sammi'}</h2><dl><div><dt>{zh?'你正在了解':'You are exploring'}</dt><dd>{l(d.sammiReviewContext.exploring)}</dd></div><div><dt>{zh?'容易忽略的关联':'Potential hidden connection'}</dt><dd>{l(d.sammiReviewContext.hidden)}</dd></div><div><dt>{zh?'可先准备':'Useful information to gather'}</dt><dd>{l(d.sammiReviewContext.gather)}</dd></div><div><dt>{zh?'值得梳理的问题':'Questions worth reviewing'}</dt><dd>{l(d.sammiReviewContext.questions)}</dd></div></dl><Link to={`${localePath('/contact')}?context=${encodeURIComponent(context)}`}>{zh?'和 Sammi 一起梳理我的退休账户转换选择':'Review My Retirement Transition with Sammi'}</Link></section>
    <section className={styles.sources}><h2>{zh?'IRS 官方资料':'Official IRS sources'}</h2>{d.officialSources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</section>
    <footer className={styles.disclaimer}><p>{zh?EDUCATIONAL_GUIDANCE_DISCLAIMER.zh:EDUCATIONAL_GUIDANCE_DISCLAIMER.en}</p><p>{zh?'本指南不判断最佳去向、Backdoor Roth 是否适合、conversion 应税金额、Form 8606 的个人处理、节税金额、新计划优劣或投资选择。':'This guide does not determine the best destination, whether to execute a Backdoor Roth, taxable conversion amounts, individual Form 8606 treatment, tax savings, whether a new plan is better, or investment selection.'}</p></footer>
  </main>
}
