import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import useDocumentMeta from '../hooks/useDocumentMeta'
import { useLocale } from '../i18n/LocaleContext'
import { FOUNDATION_QUESTIONS, FOUNDATION_SECTIONS, calculateFoundationResult } from '../features/foundationV2'
import { getLifeEvent } from '../features/lifeCapitalMap'
import styles from './FoundationV2Page.module.css'

const Button = ({ en, zh, ...props }) => <button type="button" {...props}><span>{en}</span><small lang="zh-CN">{zh}</small></button>

export default function FoundationV2Page() {
  const { localePath } = useLocale()
  const [phase,setPhase] = useState('intro'),[index,setIndex] = useState(0),[answers,setAnswers] = useState({})
  const question = FOUNDATION_QUESTIONS[index], selected = answers[question?.id]
  const result = useMemo(()=>phase==='result'?calculateFoundationResult(answers):null,[phase,answers])
  useDocumentMeta('ONYX Foundation Assessment V2 · 18-Question Readiness Scan','A bilingual, education-first scan of financial foundations, planning events, organization, and long-term capital needs.')
  const choose = (id) => { if(question.type==='single')return setAnswers((current)=>({...current,[question.id]:id}));setAnswers((current)=>{const existing=Array.isArray(current[question.id])?current[question.id]:[];const next=existing.includes(id)?existing.filter((value)=>value!==id):id==='none'?['none']:[...existing.filter((value)=>value!=='none'),id];return {...current,[question.id]:next}}) }
  const hasAnswer = question?.type==='multi'?Array.isArray(selected)&&selected.length>0:Boolean(selected)
  const restart = () => {setAnswers({});setIndex(0);setPhase('intro')}

  if(phase==='intro')return <main className={`${styles.page} page-enter`}><section className={styles.intro}><p className={styles.eyebrow}>FOUNDATION · 18 QUESTIONS</p><h1>See the foundation before choosing the next move.<span lang="zh-CN">先看清基础，再决定下一步。</span></h1><p>This short scan connects financial readiness, upcoming events, organization gaps, and long-term needs to the broader ONYX Life Capital Map.</p><p lang="zh-CN">这项简短扫描把财务准备、近期事件、资料缺口和长期需要连接到更完整的黑曜人生资本地图。</p><ul><li>No fake financial-health score · 不制造虚假健康分数</li><li>No product recommendation · 不推荐具体产品</li><li>Answers stay in memory for this visit only · 回答仅保留在本次访问内存中</li></ul><Button className={styles.primary} onClick={()=>setPhase('questions')} en="Begin Foundation Scan" zh="开始基础扫描"/><Link to={localePath('/capital-assessment')}>Use the recoverable 30-question V1 instead · 使用可恢复进度的30题V1</Link></section></main>
  if(phase==='result')return <FoundationResult result={result} localePath={localePath} onRestart={restart}/>
  const section=FOUNDATION_SECTIONS.find((item)=>item.id===question.section),progress=((index+1)/18)*100
  return <main className={`${styles.page} page-enter`}><div className={styles.shell}><aside><p>FOUNDATION PATH · 基础路径</p><ol>{FOUNDATION_SECTIONS.map((item)=><li key={item.id} aria-current={item.id===section.id?'step':undefined}>{item.name}<small lang="zh-CN">{item.nameZh}</small></li>)}</ol></aside><section className={styles.question} aria-labelledby={`foundation-${question.id}`}><header><div><strong>{question.id} · {index+1} of 18</strong><span>{section.name} · <span lang="zh-CN">{section.nameZh}</span></span></div><button type="button" onClick={restart}>Restart · 重新开始</button></header><div className={styles.progress} role="progressbar" aria-valuemin="1" aria-valuemax="18" aria-valuenow={index+1}><span style={{width:`${progress}%`}}/></div><h1 id={`foundation-${question.id}`}>{question.question}<span lang="zh-CN">{question.questionZh}</span></h1><div className={styles.options} role={question.type==='single'?'radiogroup':'group'} aria-labelledby={`foundation-${question.id}`}>{question.options.map((item)=>{const active=question.type==='multi'?Array.isArray(selected)&&selected.includes(item.id):selected===item.id;return <button type="button" key={item.id} role={question.type==='single'?'radio':undefined} aria-checked={question.type==='single'?active:undefined} aria-pressed={question.type==='multi'?active:undefined} className={active?styles.selected:undefined} onClick={()=>choose(item.id)}><span>{item.text}<small lang="zh-CN">{item.textZh}</small></span><em>{active?'Selected · 已选择':''}</em></button>})}</div>{hasAnswer&&<div className={styles.insight} aria-live="polite"><strong>LEARN · 了解</strong><p>{question.insight}</p><p lang="zh-CN">{question.insightZh}</p></div>}<footer>{index>0&&<Button className={styles.secondary} onClick={()=>setIndex(index-1)} en="Back" zh="返回"/>}<Button className={styles.primary} disabled={!hasAnswer} onClick={()=>index===17?setPhase('result'):setIndex(index+1)} en={index===17?'View My Foundation Map':'Continue'} zh={index===17?'查看基础地图':'继续'}/></footer></section></div></main>
}

function FoundationResult({result,localePath,onRestart}){return <main className={`${styles.page} page-enter`}><div className={styles.results}><header><p className={styles.eyebrow}>YOUR FOUNDATION MAP · 你的基础地图</p><h1>{result.currentCapitalPosition.title}<span lang="zh-CN">{result.currentCapitalPosition.titleZh}</span></h1><p>{result.currentCapitalPosition.summary}</p><p lang="zh-CN">{result.currentCapitalPosition.summaryZh}</p></header><ResultSection title="Immediate Attention Areas" titleZh="近期关注领域">{result.immediateAttention.length?result.immediateAttention.map((node)=><Link key={node.id} to={localePath(`/capital-map/node/${node.id.toLowerCase()}`)}>{node.id} · {node.title}<small lang="zh-CN">{node.titleZh}</small></Link>):<p>No foundational attention area was triggered; compare the Next Dollar roles without assuming one universal answer.</p>}</ResultSection><ResultSection title="Event Radar Signals" titleZh="事件雷达信号">{result.eventRadarSignals.events.map((id)=>{const event=getLifeEvent(id);return event?<Link key={id} to={localePath(`/capital-map/event/${id}`)}>{event.title}<small lang="zh-CN">{event.titleZh}</small></Link>:null})}{result.eventRadarSignals.noneKnown&&<p>None known today does not mean nothing will happen. · <span lang="zh-CN">目前没有已知事件，不代表什么都不会发生。</span></p>}{!result.eventRadarSignals.events.length&&!result.eventRadarSignals.noneKnown&&<p>No mapped event selected. Use the full Event Radar to explore planning windows.</p>}</ResultSection><ResultSection title="Long-Term Planning Signals" titleZh="长期规划信号">{result.longTermSignals.length?result.longTermSignals.map((id)=><span className={styles.signal} key={id}>{id.replaceAll('_',' ')}</span>):<p>No long-term topic selected.</p>}<Link to={localePath('/capital-map/long-term')}>Explore the 5–10 Year Planning Map · 探索5–10年规划地图</Link></ResultSection><ResultSection title="Records & Organization" titleZh="资料与组织">{result.organizationGaps.length?result.organizationGaps.map((gap)=><Link key={gap.id} to={localePath('/capital-map/node/w12')}>{gap.title}<small lang="zh-CN">{gap.titleZh}</small></Link>):<p>No organization gap was triggered by this scan.</p>}</ResultSection><ResultSection title="Suggested Capital Map Nodes" titleZh="建议探索的资本地图节点">{result.suggestedNodes.map((node)=><Link key={node.id} to={localePath(`/capital-map/node/${node.id.toLowerCase()}`)}>{node.id} · {node.title}<small lang="zh-CN">{node.titleZh}</small></Link>)}</ResultSection><section className={styles.handoff}><h2>Ask Sammi with context—not sensitive documents.<span lang="zh-CN">带上背景联系Sammi，不发送敏感文件。</span></h2><Link to={`${localePath('/contact')}?context=${encodeURIComponent(result.askSammiContext)}`}>Ask Sammi · 联系Sammi</Link></section><button type="button" className={styles.restart} onClick={onRestart}>Restart Foundation · 重新开始</button></div></main>}
function ResultSection({title,titleZh,children}){return <section className={styles.resultSection}><h2>{title}<span lang="zh-CN">{titleZh}</span></h2><div>{children}</div></section>}
