import LocaleLabel from './LocaleLabel'
import { useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useLocale } from '../i18n/LocaleContext'
import useDocumentMeta from '../hooks/useDocumentMeta'
import NotFound from './NotFound'
import JourneyConsequencePath from './JourneyConsequencePath'
import { EDUCATIONAL_DISCLAIMER, getLifeEvent, getWealthNode } from '../features/lifeCapitalMap'
import { calculateRunway, canAdvanceJourney, getHeroJourney, getNextJourneyStep, localized } from '../features/journeyEngine'
import styles from './JourneyEngine.module.css'

const UI={en:{steps:['Question','Story','Judgment','Consequence','Conclusion','Try a Tool','Next Move','Ask Sammi'],back:'Back',continue:'Continue',restart:'Restart journey',choose:'Choose an answer to continue.',story:'A real-life illustration—not a client testimonial.',facts:'What we know',reasonable:'What this thinking reveals',consequence:'Follow the consequences',conclusion:'Capital conclusion',tool:'Try a tool or experiment',next:'Explore related capital',self:'You may organize this yourself',deeper:'A deeper review may help',planned:'Planned knowledge',ask:'Bring the context, not sensitive documents.',runway:'Estimated runway',available:'Reserve after known expenses',benchmark:'ONYX uses approximately six months of core household expenses as an educational planning benchmark—not a legal rule or individualized recommendation.',monthly:'Monthly core household expense',reserve:'Available liquid reserve',known:'Known near-term large expenses',empty:'Enter all three values to see an educational estimate.',invalid:'Use a monthly expense above zero and non-negative amounts.',months:'months',private:'Inputs stay on this page only and are not saved or submitted.'},zh:{steps:['问题','故事','判断','后果','结论','尝试工具','下一步','联系Sammi'],back:'返回',continue:'继续',restart:'重新开始旅程',choose:'请选择后再继续。',story:'真实生活示例，并非客户见证。',facts:'已知事实',reasonable:'这个想法揭示了什么',consequence:'沿着后果向前看',conclusion:'资本结论',tool:'尝试一个工具或实验',next:'探索相关资本',self:'你可能可以先自行整理',deeper:'进一步梳理可能有帮助',planned:'计划中的知识内容',ask:'带上问题背景即可，请不要发送敏感文件。',runway:'预计资金跑道',available:'扣除已知支出后的储备',benchmark:'黑曜采用约六个月核心支出作为教育性规划基准，并非法律规则或个性化建议。',monthly:'每月核心家庭支出',reserve:'可用流动储备',known:'近期已知大额支出',empty:'请填写三个数值，查看教育性估算。',invalid:'月支出需大于零，其他金额不得为负数。',months:'个月',private:'输入仅停留在当前页面，不会保存或提交。'}}

function RunwayTool({ui}){const [values,setValues]=useState({monthlyExpense:'',liquidReserve:'',knownExpenses:''});const untouched=Object.values(values).every((value)=>value==='');const result=useMemo(()=>calculateRunway(values),[values]);return <div><p className={styles.privacy}>{ui.private}</p><div className={styles.runwayInputs}>{[['monthlyExpense',ui.monthly],['liquidReserve',ui.reserve],['knownExpenses',ui.known]].map(([key,label])=><label key={key}>{label}<input type="number" min="0" inputMode="decimal" value={values[key]} onChange={(event)=>setValues((current)=>({...current,[key]:event.target.value}))}/></label>)}</div>{untouched?<p className={styles.toolMessage}>{ui.empty}</p>:!result.valid?<p className={`${styles.toolMessage} ${styles.invalid}`} role="alert">{ui.invalid}</p>:<div className={styles.runwayResult} aria-live="polite"><article><span>{ui.runway}</span><b>{result.runwayMonths.toLocaleString(undefined,{maximumFractionDigits:1})} {ui.months}</b></article><article><span>{ui.available}</span><b>${result.availableReserve.toLocaleString(undefined,{maximumFractionDigits:0})}</b></article></div>}<p className={styles.benchmark}>{ui.benchmark}</p></div>}

function ChecklistTool({items,locale}){const [checked,setChecked]=useState([]);return <div className={styles.checklist}>{items.map((item,index)=><label key={index}><input type="checkbox" checked={checked.includes(index)} onChange={()=>setChecked((current)=>current.includes(index)?current.filter((value)=>value!==index):[...current,index])}/><span>{localized(item,locale)}</span></label>)}</div>}

export default function JourneyScenarioPage(){const {id}=useParams(),{locale,localePath}=useLocale(),journey=getHeroJourney(id);const [step,setStep]=useState(0),[opening,setOpening]=useState(''),[judgment,setJudgment]=useState('');const ui=UI[locale==='zh'?'zh':'en'];useDocumentMeta(journey?`${localized(journey.title,locale)} | ONYX Life Capital Journey`:'Journey not found',journey?localized(journey.subtitle,locale):'');if(!journey)return <NotFound/>;const journeyState={openingChoice:opening,judgmentChoice:judgment},canContinue=canAdvanceJourney(step,journeyState);const next=()=>setStep((current)=>getNextJourneyStep(current,journeyState));const restart=()=>{setStep(0);setOpening('');setJudgment('')};return <main className={`${styles.shell} ${styles.scenarioShell} page-enter`}><header className={styles.scenarioHeader}><Link to={localePath('/capital-map/journey')}>← {ui.back}</Link><p><LocaleLabel value={journey.stage} /> · <LocaleLabel value={journey.domain} /></p><h1>{localized(journey.title,locale)}</h1><h2>{localized(journey.subtitle,locale)}</h2></header><nav className={styles.stepNav} aria-label="Journey progress">{ui.steps.map((label,index)=><button key={label} type="button" disabled={index>step} aria-current={index===step?'step':undefined} onClick={()=>index<=step&&setStep(index)}><span>{index+1}</span>{label}</button>)}</nav><section className={styles.stagePanel} aria-live="polite">
{step===0&&<><span className={styles.eyebrow}>{ui.steps[0]}</span><h2>{localized(journey.openingQuestion,locale)}</h2><div className={styles.choiceList} role="radiogroup" aria-label={localized(journey.openingQuestion,locale)}>{journey.openingChoices.map((item)=><button key={item.id} type="button" role="radio" aria-checked={opening===item.id} onClick={()=>setOpening(item.id)}>{localized(item.label,locale)}</button>)}</div></>}
{step===1&&<><span className={styles.eyebrow}>{ui.steps[1]}</span><p className={styles.note}>{ui.story}</p><blockquote>{localized(journey.story,locale)}</blockquote><h3>{ui.facts}</h3><ul className={styles.factList}>{journey.storyFacts.map((fact,index)=><li key={index}>{localized(fact,locale)}</li>)}</ul></>}
{step===2&&<><span className={styles.eyebrow}>{ui.steps[2]}</span><h2>{localized(journey.judgmentQuestion,locale)}</h2><div className={styles.choiceList} role="radiogroup" aria-label={localized(journey.judgmentQuestion,locale)}>{journey.judgmentChoices.map((item)=><button key={item.id} type="button" role="radio" aria-checked={judgment===item.id} onClick={()=>setJudgment(item.id)}>{localized(item.label,locale)}</button>)}</div>{judgment&&<div className={styles.feedback}><b>{ui.reasonable}</b><p>{localized(journey.judgmentFeedback[judgment],locale)}</p></div>}</>}
{step===3&&<><span className={styles.eyebrow}>{ui.steps[3]}</span><h2>{ui.consequence}</h2><JourneyConsequencePath paths={journey.consequencePaths} locale={locale}/></>}
{step===4&&<><span className={styles.eyebrow}>{ui.steps[4]}</span><h2>{ui.conclusion}</h2><p className={styles.capitalConclusion}>{localized(journey.capitalConclusion,locale)}</p><p className={styles.principle}>{localized(journey.principle,locale)}</p></>}
{step===5&&<><span className={styles.eyebrow}>{ui.steps[5]}</span><h2>{localized(journey.tool.title,locale)}</h2>{journey.tool.description&&<p>{localized(journey.tool.description,locale)}</p>}{journey.tool.kind==='runway'?<RunwayTool ui={ui}/>:<ChecklistTool items={journey.tool.items} locale={locale}/>}</>}
{step===6&&<><span className={styles.eyebrow}>{ui.steps[6]}</span><h2>{ui.next}</h2><div className={styles.relatedLinks}>{journey.relatedNodes.map((nodeId)=>{const node=getWealthNode(nodeId);return node?<Link key={nodeId} to={localePath(`/capital-map/node/${nodeId.toLowerCase()}`)}>{nodeId} · {locale==='zh'?node.titleZh:node.title}</Link>:null})}{journey.relatedEvents.map((eventId)=>{const event=getLifeEvent(eventId);return event?<Link key={eventId} to={localePath(`/capital-map/event/${eventId}`)}>{locale==='zh'?event.titleZh:event.title}</Link>:null})}</div><div className={styles.guidance}><article><b>{ui.self}</b><p>{localized(journey.selfManageGuidance,locale)}</p></article><article><b>{ui.deeper}</b><p>{localized(journey.deeperReviewGuidance,locale)}</p></article></div><h3>{ui.planned}</h3><ul>{journey.relatedInsights.map((item,index)=><li key={index}>{localized(item,locale)}</li>)}</ul></>}
{step===7&&<><span className={styles.eyebrow}>{ui.steps[7]}</span><h2>{ui.ask}</h2><p>{localized(journey.principle,locale)}</p><Link className={styles.askLink} to={`${localePath('/contact')}?context=${encodeURIComponent(journey.askSammiContext)}`}>{ui.steps[7]}</Link><button type="button" className={styles.restart} onClick={restart}>{ui.restart}</button></>}
</section><div className={styles.controls}>{step>0&&<button type="button" onClick={()=>setStep((current)=>current-1)}>{ui.back}</button>}{step<7&&<button type="button" disabled={!canContinue} onClick={next}>{ui.continue}</button>}{!canContinue&&<span>{ui.choose}</span>}</div><footer className={styles.disclaimer}><p>{EDUCATIONAL_DISCLAIMER[locale==='zh'?'zh':'en']}</p></footer></main>}
