import { useMemo, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { useLocale } from '../i18n/LocaleContext'
import useDocumentMeta from '../hooks/useDocumentMeta'
import { EDUCATIONAL_GUIDANCE_DISCLAIMER } from '../data/v3Brand'
import { calculateBusinessProfit, compareStartingAges, createGuideResult, getKnowledgeGuide, localize } from '../features/knowledgeGuides'
import styles from './KnowledgeGuidePage.module.css'

const money = new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0})

function BusinessProfitTool({ zh }){
  const [values,setValues]=useState({revenue:'',expenses:''}); const result=calculateBusinessProfit(values.revenue,values.expenses)
  return <section className={styles.calculator}><h3>{zh?'业务利润概念图':'Business Profit Lens'}</h3><p>{zh?'只展示收入减去合理业务费用后的估算结果，不计算个人税负。':'Shows revenue minus estimated legitimate business expenses. It does not calculate personal tax liability.'}</p><div className={styles.inputs}><label>{zh?'预计业务收入':'Expected business revenue'}<input inputMode="decimal" value={values.revenue} onChange={(e)=>setValues({...values,revenue:e.target.value})}/></label><label>{zh?'预计合理业务费用':'Estimated legitimate expenses'}<input inputMode="decimal" value={values.expenses} onChange={(e)=>setValues({...values,expenses:e.target.value})}/></label></div>{result&&<div className={styles.calcResult}><span>{money.format(result.revenue)} − {money.format(result.expenses)}</span><strong>{zh?'税前业务利润估算':'Estimated business profit before personal tax'}: {money.format(result.profit)}</strong><p>{zh?'更多利润可能同时意味着更多收入、额外税务义务、预估税需要、退休规划机会以及管理工作。':'More profit may mean more income, added tax obligations, estimated-tax needs, retirement opportunities, and administration.'}</p></div>}</section>
}

function CostOfWaitingTool({ zh }){
  const [values,setValues]=useState({monthly:'250',endAge:'18',rate:'5'}); const rows=compareStartingAges(values.monthly,values.endAge,values.rate)
  return <section className={styles.calculator}><h3>{zh?'时间的示意作用':'Illustrating the Role of Time'}</h3><div className={styles.inputs}><label>{zh?'每月投入':'Monthly contribution'}<input inputMode="decimal" value={values.monthly} onChange={(e)=>setValues({...values,monthly:e.target.value})}/></label><label>{zh?'计算至年龄':'Ending age'}<input inputMode="numeric" value={values.endAge} onChange={(e)=>setValues({...values,endAge:e.target.value})}/></label><label>{zh?'示意年回报率（%）':'Illustrative annual return (%)'}<input inputMode="decimal" value={values.rate} onChange={(e)=>setValues({...values,rate:e.target.value})}/></label></div>{rows.every((row)=>Number.isFinite(row.value))&&<div className={styles.compare}>{rows.map((row)=><article key={row.startAge}><span>{zh?`${row.startAge} 岁开始`:`Start at age ${row.startAge}`}</span><strong>{money.format(row.value)}</strong></article>)}</div>}<p className={styles.toolNote}>{zh?'仅为示意。回报不受保证，且未包括所有税费、产品成本或助学金影响。':'Illustrative only. Returns are not guaranteed. Does not include all taxes, fees, product costs, or financial-aid effects.'}</p></section>
}

export default function KnowledgeGuidePage(){
  const { guideId }=useParams(); const {locale,localePath}=useLocale(); const zh=locale==='zh'; const guide=getKnowledgeGuide(guideId)
  const [explored,setExplored]=useState([]); const result=useMemo(()=>guide?createGuideResult(guide,explored):null,[guide,explored])
  useDocumentMeta(guide?`${localize(guide.title,locale)} · ONYX`:'Knowledge Guide · ONYX',guide?localize(guide.answer,locale):'')
  if(!guide)return <main className={styles.missing}><h1>{zh?'未找到该知识指南':'Knowledge guide not found'}</h1><Link to={localePath('/')}>{zh?'返回首页':'Back home'}</Link></main>
  const toggle=(topic)=>setExplored((current)=>current.includes(topic)?current.filter((item)=>item!==topic):[...current,topic])
  return <main className={`${styles.page} page-enter`}>
    <header className={styles.hero}><p>{zh?'ONYX 知识指南':'ONYX KNOWLEDGE GUIDE'}</p><h1>{localize(guide.title,locale)}</h1><blockquote>{localize(guide.entry,locale)}</blockquote><div className={styles.quickAnswer}><span>{zh?'先看清问题':'THE ISSUE IN 60 SECONDS'}</span><p>{localize(guide.answer,locale)}</p></div></header>
    <nav className={styles.jump} aria-label={zh?'指南目录':'Guide sections'}>{[['asked','1'],['connects','2'],['overlooked','3'],['dollars','4'],['tradeoffs','5'],['before','6'],['next','7']].map(([id,num])=><a key={id} href={`#${id}`}>{num}</a>)}</nav>
    <section id="asked" className={styles.story}><p className={styles.eyebrow}>{zh?'你提出的问题':'WHAT YOU ASKED'}</p><h2>{localize(guide.title,locale)}</h2><p>{localize(guide.story,locale)}</p>{guide.entryChoices&&<div className={styles.topicChoices}>{localize(guide.entryChoices,locale).map((choice)=><button type="button" aria-pressed={explored.includes(choice)} key={choice} onClick={()=>toggle(choice)}>{choice}</button>)}</div>}<strong>{guide.id==='second-income-engine'?(zh?'实体 ≠ 生意　·　1099 ≠ 税务策略':'ENTITY ≠ BUSINESS · 1099 ≠ TAX STRATEGY'):guide.id==='business-payroll-retirement'?(zh?'业务利润 ≠ 可以随意支出的现金　·　S CORPORATION ≠ 自动节税':'BUSINESS PROFIT ≠ CASH AVAILABLE TO SPEND · S CORPORATION ≠ AUTOMATIC TAX SAVINGS'):localize(guide.signature,locale)}</strong></section>
    <section id="connects" className={styles.section}><p className={styles.eyebrow}>{zh?'它连接到什么':'WHAT IT CONNECTS TO'}</p><h2>{zh?'一项决定，会穿过整个家庭资本系统。':'One decision can travel through the family-capital system.'}</h2><div className={styles.flow}>{localize(guide.flow,locale).map((item,index)=><span key={item}>{item}{index<localize(guide.flow,locale).length-1&&<i aria-hidden="true">→</i>}</span>)}</div><div className={styles.topicChoices}>{localize(guide.topics,locale).map((topic)=><button type="button" aria-pressed={explored.includes(topic)} key={topic} onClick={()=>toggle(topic)}>{topic}</button>)}</div></section>
    <section id="overlooked" className={styles.signature}><p className={styles.eyebrow}>{zh?'你可能还不知道要问的问题':'THE QUESTION YOU DIDN’T KNOW TO ASK'}</p><h2>“{localize(guide.signature,locale)}”</h2>{localize(guide.overlooked,locale).map((item)=><p key={item}>{item}</p>)}</section>
    <section id="dollars" className={styles.section}><p className={styles.eyebrow}>{zh?'为什么它与金钱有关':'WHY IT MATTERS IN DOLLARS'}</p>{guide.tool==='businessProfit'?<BusinessProfitTool zh={zh}/>:guide.tool==='costOfWaiting'?<CostOfWaitingTool zh={zh}/>:<div className={styles.moneyFlow}>{guide.id==='rental-equity'?localize({en:['Sale price','Selling costs','Debt payoff','Potential tax consequences','Capital available for its next job'],zh:['售价','出售成本','偿还债务','潜在税务后果','可投入下一任务的资本']},locale).map((item,index)=><span key={item}>{index?`− ${item}`:item}</span>):<p>{zh?'报酬、Payroll、税务合规、业务现金流和退休计划会相互影响；本指南不估算个性化税负或节税金额。':'Compensation, payroll, tax compliance, business cash flow, and retirement design interact. This guide does not estimate individualized tax liability or savings.'}</p>}</div>}</section>
    <section id="tradeoffs" className={styles.section}><p className={styles.eyebrow}>{zh?'你的选择与取舍':'YOUR CHOICES & TRADE-OFFS'}</p><div className={styles.tradeoffs}>{localize(guide.tradeoffs,locale).map((item)=><article key={item.title}><h3>{item.title}</h3><p>{item.body}</p></article>)}</div></section>
    <section id="before" className={styles.before}><p className={styles.eyebrow}>{zh?'行动之前':'BEFORE YOU ACT'}</p><h2>{zh?'先整理信息，不上传敏感文件。':'Gather the useful facts—without uploading sensitive files.'}</h2><ul>{localize(guide.gather,locale).map((item)=><li key={item}>{item}</li>)}</ul>{guide.officialSources?.map((source)=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}</section>
    <section id="next" className={styles.next}><p className={styles.eyebrow}>{zh?'你的下一步':'YOUR NEXT MOVE'}</p><ol>{localize(guide.nextMoves,locale).map((item)=><li key={item}>{item}</li>)}</ol><div className={styles.handoff}><span>{zh?'你探索了':'YOU EXPLORED'}</span><h2>{explored.length?explored.join(' + '):localize(guide.title,locale)}</h2><p>{zh?'可能需要补充的信息：':'Useful information to gather: '} {localize(guide.gather,locale).slice(0,3).join(' · ')}</p><Link to={`${localePath('/contact')}?context=${encodeURIComponent(result.sammiReviewContext)}`}>{localize(guide.cta,locale)}</Link></div></section>
    <section className={styles.related}><p className={styles.eyebrow}>{zh?'这也连接到':'THIS ALSO CONNECTS TO'}</p>{guide.related.map((id)=>{const item=getKnowledgeGuide(id);return <Link key={id} to={localePath(`/guides/${id}`)}><strong>{localize(item.title,locale)}</strong><span>{zh?'继续探索 →':'Explore connection →'}</span></Link>})}</section>
    <footer className={styles.disclaimer}><button type="button" onClick={()=>window.print()}>{zh?'打印关键摘要':'Print key summary'}</button><p>{zh?EDUCATIONAL_GUIDANCE_DISCLAIMER.zh:EDUCATIONAL_GUIDANCE_DISCLAIMER.en}</p><p>{zh?'输入仅保留在当前页面内存中；刷新或离开页面即清除。':'Inputs remain only in this page’s memory and clear on refresh or navigation.'}</p></footer>
  </main>
}
